version: '3.4'

services:
  pixel.api:
    image: ${DOCKER_REGISTRY-}pixelapi
    build:
      context: .
      dockerfile: Pixel.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  storageservice:
    image: ${DOCKER_REGISTRY-}storageservice
    build:
      context: .
      dockerfile: StorageService/StorageService/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"
    restart: unless-stopped

volumes:
  rabbitmq_data:
  rabbitmq_log:
